# This spec file was generated by KDevelop
# Please report any problem to KDevelop Team <kdevelop-devel@kdevelop.org>
# Thanks to Matthias Saou for his explanations on http://freshrpms.net/docs/fight.html

Summary: 		LinM visual shell
Name: 			linm
Version: 		0.8
Release:		1
Vendor: 		Shells
#Copyright: 	GPL
License: 		GPL
Group: 			System Environment
Packager: 		Byoungyoung, La
BuildRoot: 		%{_tmppath}/%{name}-%{version}-root
Source: 		linm-0.8-1.tar.gz
URL:			http://mls.kldp.net
BuildRequires:	ncurses-devel >= 5.2.0, openssl-devel >= 0.9.6, samba-common >= 3.0.0
Requires: 		ncurses >= 5.2.0, openssl >= 0.9.6, samba-common >= 3.0.0

%description
LinM is a visaul file manager. 
It's a feature rich full-screen text mode application that allows you to copy, move and
delete files and whole directory trees, search for files and run commands in the subshell.

LinM is best features are its ability to FTP, SFTP, view tar and zip, alz files, and to poke into RPMs for specific files, and DEB package.

%prep
%setup -q -n %{name}-%{version}


%build
export CFLAGS="$RPM_OPT_FLAGS" CXXFLAGS="$RPM_OPT_FLAGS" 
%configure \
	     --host=%{_host} --build=%{_build} \
	     --target=%{_target_platform} \
	     --program-prefix=%{?_program_prefix} \
	     --prefix=%{_prefix} \
	     --exec-prefix=%{_exec_prefix} \
	     --bindir=%{_bindir} \
	     --sbindir=%{_sbindir} \
	     --sysconfdir=%{_sysconfdir} \
	     --datadir=%{_datadir} \
	     --includedir=%{_includedir} \
	     --datadir=%{_datadir} \
	     --libexecdir=%{_libexecdir}
	     
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT
mkdir $RPM_BUILD_ROOT
mkdir $RPM_BUILD_ROOT/etc
mkdir $RPM_BUILD_ROOT/etc/linm
mkdir $RPM_BUILD_ROOT/etc/profile.d
make DESTDIR="$RPM_BUILD_ROOT" install

%clean
rm -rf $RPM_BUILD_ROOT

#%post -p /sbin/ldconfig
#%postun -p /sbin/ldconfig

%files
%defattr(-, root, root)

%doc AUTHORS COPYING ChangeLog README README.ko_euckr README.ko_utf8

%{_bindir}/*

%config %{_sysconfdir}/linm/*
%{_sysconfdir}/profile.d/*
%{_datadir}/locale/*/LC_MESSAGES/*
%{_datadir}/applications/*
%{_datadir}/pixmaps/*

%dir %{_libdir}/*
%dir %{_datadir}/*

%changelog
* Sun Feb 10 2008 Byoungyoung La, <la9527@yahoo.co.kr>
- 0.8.1 version make
* Mon Dec 31 2007 Byoungyoung La, <la9527@yahoo.co.kr>
- 0.8 version make
* Mon Jan 1 2007 Byoungyoung La, <la9527@yahoo.co.kr>
- 0.7.12 version make
- samba supported.
* Sat Sep 9 2006 Byoungyoung La, <la9527@yahoo.co.kr>
- 0.7.11 version make
- bugfix and sftp, ftp support.
* Sat Apr 22 2006 Byoungyoung La, <la9527@yahoo.co.kr>
- 0.7.10 version make
* Sat Apr 22 2006 Byoungyoung La, <la9527@yahoo.co.kr>
- 0.7.9 version make
* Sun Apr 2 2006 Byoungyoung La, <la9527@yahoo.co.kr>
- 0.7.8 version make
* Mon Jan 30 2006 Byoungyoung La, <la9527@yahoo.co.kr>
- 0.7.7 version make
* Fri Jul 29 2005 Byoungyoung La, <la9527@yahoo.co.kr>
- 0.7.6 version make
* Fri Jul 29 2005 Byoungyoung La, <la9527@yahoo.co.kr>
- 0.6.7 version make
* Sun Jul 24 2005 Byoungyoung La, <la9527@yahoo.co.kr>
- 0.6.5 version make
* Mon Jul 11 2005 Byoungyoung La, <la9527@yahoo.co.kr>
- 0.6 version make
* Sun Nov 21 2004 Byoungyoung La, <la9527@yahoo.co.kr>
- 0.5 version make
* Sun Nov 21 2004 Byoungyoung La, <la9527@yahoo.co.kr>
- 0.4.5 version make
* Sun Nov 21 2004 Byoungyoung La, <la9527@yahoo.co.kr>
- 0.3 version make 
* Sun Sep 12 2004 Byoungyoung La, <la9527@yahoo.co.kr>
- first make rpm package.
