default: all

all: build

build:
	cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$(shell pwd)/output/install -DDEBUG_MODE:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -G "CodeBlocks - Unix Makefiles" --build $(shell pwd)/cmake-build-debug $(shell pwd)

clean:
	cmake --build $(shell pwd)/cmake-build-debug --target clean
	rm -f CMakeCache.txt

