/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_MainWindowPanel (void)
{
  GtkWidget *MainWindowPanel;
  GtkWidget *vbox1;
  GtkWidget *menubar_mainmenu;
  GtkWidget *menuitem1;
  GtkWidget *menu1;
  GtkWidget *_________________n_1;
  GtkWidget *_______o_1;
  GtkWidget *_______s_1;
  GtkWidget *___________________________a_1;
  GtkWidget *separatormenuitem1;
  GtkWidget *__________q_1;
  GtkWidget *menuitem2;
  GtkWidget *menu2;
  GtkWidget *_____________t_1;
  GtkWidget *_______c_1;
  GtkWidget *______________p_1;
  GtkWidget *__________d_1;
  GtkWidget *menuitem3;
  GtkWidget *menu3;
  GtkWidget *menuitem4;
  GtkWidget *menu4;
  GtkWidget *about1;
  GtkWidget *entry_currentpath;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview_dir;
  GtkWidget *statusbar_msg;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  MainWindowPanel = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (MainWindowPanel, "MainWindowPanel");
  gtk_window_set_title (GTK_WINDOW (MainWindowPanel), _("LinM GTK Panel"));
  gtk_window_set_default_size (GTK_WINDOW (MainWindowPanel), 800, 600);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (MainWindowPanel), vbox1);

  menubar_mainmenu = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar_mainmenu, "menubar_mainmenu");
  gtk_widget_show (menubar_mainmenu);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar_mainmenu, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_set_name (menuitem1, "menuitem1");
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar_mainmenu), menuitem1);

  menu1 = gtk_menu_new ();
  gtk_widget_set_name (menu1, "menu1");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menu1);

  _________________n_1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_set_name (_________________n_1, "_________________n_1");
  gtk_widget_show (_________________n_1);
  gtk_container_add (GTK_CONTAINER (menu1), _________________n_1);

  _______o_1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_set_name (_______o_1, "_______o_1");
  gtk_widget_show (_______o_1);
  gtk_container_add (GTK_CONTAINER (menu1), _______o_1);

  _______s_1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_set_name (_______s_1, "_______s_1");
  gtk_widget_show (_______s_1);
  gtk_container_add (GTK_CONTAINER (menu1), _______s_1);

  ___________________________a_1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_set_name (___________________________a_1, "___________________________a_1");
  gtk_widget_show (___________________________a_1);
  gtk_container_add (GTK_CONTAINER (menu1), ___________________________a_1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separatormenuitem1, "separatormenuitem1");
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menu1), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  __________q_1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_set_name (__________q_1, "__________q_1");
  gtk_widget_show (__________q_1);
  gtk_container_add (GTK_CONTAINER (menu1), __________q_1);

  menuitem2 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_set_name (menuitem2, "menuitem2");
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menubar_mainmenu), menuitem2);

  menu2 = gtk_menu_new ();
  gtk_widget_set_name (menu2, "menu2");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menu2);

  _____________t_1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_set_name (_____________t_1, "_____________t_1");
  gtk_widget_show (_____________t_1);
  gtk_container_add (GTK_CONTAINER (menu2), _____________t_1);

  _______c_1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_set_name (_______c_1, "_______c_1");
  gtk_widget_show (_______c_1);
  gtk_container_add (GTK_CONTAINER (menu2), _______c_1);

  ______________p_1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_set_name (______________p_1, "______________p_1");
  gtk_widget_show (______________p_1);
  gtk_container_add (GTK_CONTAINER (menu2), ______________p_1);

  __________d_1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_set_name (__________d_1, "__________d_1");
  gtk_widget_show (__________d_1);
  gtk_container_add (GTK_CONTAINER (menu2), __________d_1);

  menuitem3 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_set_name (menuitem3, "menuitem3");
  gtk_widget_show (menuitem3);
  gtk_container_add (GTK_CONTAINER (menubar_mainmenu), menuitem3);

  menu3 = gtk_menu_new ();
  gtk_widget_set_name (menu3, "menu3");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem3), menu3);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_set_name (menuitem4, "menuitem4");
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar_mainmenu), menuitem4);

  menu4 = gtk_menu_new ();
  gtk_widget_set_name (menu4, "menu4");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menu4);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_set_name (about1, "about1");
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menu4), about1);

  entry_currentpath = gtk_entry_new ();
  gtk_widget_set_name (entry_currentpath, "entry_currentpath");
  gtk_widget_show (entry_currentpath);
  gtk_box_pack_start (GTK_BOX (vbox1), entry_currentpath, FALSE, FALSE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_currentpath), 8226);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  treeview_dir = gtk_tree_view_new ();
  gtk_widget_set_name (treeview_dir, "treeview_dir");
  gtk_widget_show (treeview_dir);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview_dir);

  statusbar_msg = gtk_statusbar_new ();
  gtk_widget_set_name (statusbar_msg, "statusbar_msg");
  gtk_widget_show (statusbar_msg);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar_msg, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) _________________n_1, "activate",
                    G_CALLBACK (on__________________n_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _______o_1, "activate",
                    G_CALLBACK (on________o_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _______s_1, "activate",
                    G_CALLBACK (on________s_1_activate),
                    NULL);
  g_signal_connect ((gpointer) ___________________________a_1, "activate",
                    G_CALLBACK (on____________________________a_1_activate),
                    NULL);
  g_signal_connect ((gpointer) __________q_1, "activate",
                    G_CALLBACK (on___________q_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _____________t_1, "activate",
                    G_CALLBACK (on______________t_1_activate),
                    NULL);
  g_signal_connect ((gpointer) _______c_1, "activate",
                    G_CALLBACK (on________c_1_activate),
                    NULL);
  g_signal_connect ((gpointer) ______________p_1, "activate",
                    G_CALLBACK (on_______________p_1_activate),
                    NULL);
  g_signal_connect ((gpointer) __________d_1, "activate",
                    G_CALLBACK (on___________d_1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MainWindowPanel, MainWindowPanel, "MainWindowPanel");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, menubar_mainmenu, "menubar_mainmenu");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, menu1, "menu1");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, _________________n_1, "_________________n_1");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, _______o_1, "_______o_1");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, _______s_1, "_______s_1");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, ___________________________a_1, "___________________________a_1");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, __________q_1, "__________q_1");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, menu2, "menu2");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, _____________t_1, "_____________t_1");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, _______c_1, "_______c_1");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, ______________p_1, "______________p_1");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, __________d_1, "__________d_1");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, menuitem3, "menuitem3");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, menu3, "menu3");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, menu4, "menu4");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, about1, "about1");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, entry_currentpath, "entry_currentpath");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, treeview_dir, "treeview_dir");
  GLADE_HOOKUP_OBJECT (MainWindowPanel, statusbar_msg, "statusbar_msg");

  gtk_window_add_accel_group (GTK_WINDOW (MainWindowPanel), accel_group);

  return MainWindowPanel;
}

GtkWidget*
create_aboutdialog1 (void)
{
  GtkWidget *aboutdialog1;
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");

  aboutdialog1 = gtk_about_dialog_new ();
  gtk_widget_set_name (aboutdialog1, "aboutdialog1");
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (aboutdialog1), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (aboutdialog1), _("LinM Gtk Panel"));
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (aboutdialog1), translators);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog1, aboutdialog1, "aboutdialog1");

  return aboutdialog1;
}

