#!/bin/sh
# postrm script for witt-flash-plugin
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

#DEBHELPER#

if [ -w /etc/bash.bashrc ]; then
	if [ -d /tmp ]; then
		rm -f /tmp/bash.bashrc
		cat /etc/bash.bashrc | grep -v 'alias linm=' >> /tmp/bash.bashrc
		cp /tmp/bash.bashrc /etc/bash.bashrc
		rm -f /tmp/bash.bashrc
	fi
fi

exit 0


